{ config, pkgs, ... }:

let
  # Define a VS Code package with pre-installed extensions.
  vscodeWithExtensions = pkgs.vscode-with-extensions.override {
    extensions = with pkgs.vscode-extensions; [
      jojihatzz.codemapper
      jojihatzz.c0mmentremover
      jojihatzz.grandblue
    ];
  };
in {
  # Import essential configuration modules: hardware settings, base options,
  # (optionally Hyprland desktop), and the user configuration.
  imports = [
    ./hardware.nix                      # Hardware configuration generated by nixos-generate-config.
    ../../modules/base.nix              # Global system settings, fonts, and security settings.
    #../../modules/desktop/hyprland.nix    # Hyprland-specific desktop configuration.
    ../../modules/users/joji.nix        # User "joji" configuration.
  ];

  # Bootloader settings: enable systemd-boot and allow EFI variable modifications.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enable essential services.
  services.networkmanager.enable = true;  # Manage network connections.
  networking.firewall.enable = true;        # Default firewall settings.
  services.bluetooth.enable = true;         # Bluetooth support.
  services.printing.enable = true;          # Enable printing service.
  services.fwupd.enable = true;             # Firmware update support.

  # Set system locale, timezone, and keyboard map.
  time.timeZone = "Europe/Athens";
  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "us";

  # Install system-wide packages.
  environment.systemPackages = with pkgs; [
    git
    google-chrome
    vlc
    mediawriter
    spotify
    neovim
    discord
    neofetch
    starship
    vscodeWithExtensions  # VS Code with customized extensions.
    htop
    python313
    pipewire
    gufw
  ];

  # Configure Pipewire for audio (and enable ALSA support).
  services.pipewire = {
    enable = true;
    alsa.enable = true;
  };

  # Additional configuration options can be added here.
}
